apiVersion: v1
kind: Service
metadata:
  name: portfolio-web
  namespace: portfolio
  labels:
    app: portfolio
    component: web
spec:
  type: ClusterIP
  selector:
    app: portfolio
    component: web
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
